// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EuIDqzJcRJLZujM5ByPlxhrs8W1jxuY',
    appId: '1:12315948631:web:e4520c5665bf5cb6789512',
    messagingSenderId: '12315948631',
    projectId: 'snake-game-4fd3f',
    authDomain: 'snake-game-4fd3f.firebaseapp.com',
    storageBucket: 'snake-game-4fd3f.appspot.com',
    measurementId: 'G-V5F3WV1X2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyw2Mr-ryI2rPO4Eb5vDiCXR8q9QD9TE',
    appId: '1:12315948631:android:1e9fdb9af2e092ce789512',
    messagingSenderId: '12315948631',
    projectId: 'snake-game-4fd3f',
    storageBucket: 'snake-game-4fd3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHFWGFWBgVOL83Cj4osg4B2U2U6Mqufo',
    appId: '1:12315948631:ios:b2c0cece79e9a4b6789512',
    messagingSenderId: '12315948631',
    projectId: 'snake-game-4fd3f',
    storageBucket: 'snake-game-4fd3f.appspot.com',
    iosBundleId: 'com.tanyamakuwekuwe.snakeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHFWGFWBgVOL83Cj4osg4B2U2U6Mqufo',
    appId: '1:12315948631:ios:b2c0cece79e9a4b6789512',
    messagingSenderId: '12315948631',
    projectId: 'snake-game-4fd3f',
    storageBucket: 'snake-game-4fd3f.appspot.com',
    iosBundleId: 'com.tanyamakuwekuwe.snakeGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EuIDqzJcRJLZujM5ByPlxhrs8W1jxuY',
    appId: '1:12315948631:web:d179ce8bf77bce6b789512',
    messagingSenderId: '12315948631',
    projectId: 'snake-game-4fd3f',
    authDomain: 'snake-game-4fd3f.firebaseapp.com',
    storageBucket: 'snake-game-4fd3f.appspot.com',
    measurementId: 'G-PH55S8MV6J',
  );

}